# Generated by Django 3.2.5 on 2021-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyMeals', '0002_alter_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
